### ISSUE TITLE
Define MSRV 

### ISSUE THREAD

**Issue by DenuxPlays** [ProbablyClem/utoipauto#35]
Hey,

I noticed that we do not define a MSRV for all of our three crates.
I think its a good idea to do that.

We have to look which rust version we want to support.

## TODOs

- [x] test which rust version the crate compiles in and all test succeed
- [x] update ci to test the latest rust versiond and our msrv

## General Workspace improvements

We now have moved to a cargo workspace and want to improve it a bit.

- [x] introduce a `rustfmt.toml`
- [x] introduce a .editorconfig

**rustfmt.toml**

```toml
edition = "2021"
max_width = 120
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
#group_imports = "StdExternalCrate" # currently a nightly feature
```

**.editorconfig**

```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4
max_line_length = 120

[*.md]
# double whitespace at end of line
# denotes a line break in Markdown
trim_trailing_whitespace = false

[{*.yml,*.yaml}]
indent_size = 2
```
